apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  restartPolicy: Always
  containers:
  - name: ubuntu-container
    image: ubuntu
    command:
    - /bin/bash
    - -ec
    - touch /tmp/ready.txt; sleep 10; rm -f /tmp/ready.txt; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/ready.txt
      initialDelaySeconds: 5
      periodSeconds: 5
